---
shared:
  :appropriate_bodies:
    - id
    - name
    - created_at
    - updated_at
    - dfe_sign_in_organisation_id
    - dqt_id
  :induction_extensions:
    - id
    - teacher_id
    - number_of_terms
    - created_at
    - updated_at
  :induction_periods:
    - id
    - appropriate_body_id
    - started_on
    - finished_on
    - created_at
    - updated_at
    - induction_programme
    - training_programme
    - number_of_terms
    - range
    - teacher_id
    - outcome
    - fail_confirmation_sent_on
  :teachers:
    - id
    - created_at
    - updated_at
    - trn
    - trnless
    - trs_qts_awarded_on
    - trs_qts_status_description
    - trs_induction_status
    - trs_initial_teacher_training_provider_name
    - trs_initial_teacher_training_end_date
    - trs_data_last_refreshed_at
    - trs_deactivated
    - trs_induction_start_date
    - trs_induction_completed_date
  :pending_induction_submission_batches:
    - id
    - appropriate_body_id
    - batch_status
    - batch_type
    - created_at
    - updated_at
    - file_size
    - file_type
    - uploaded_count
    - processed_count
    - errored_count
    - claimed_count
    - released_count
    - passed_count
