---
shared:
  :teachers:
    - trn
    - trs_first_name
    - trs_last_name
    - corrected_name
    - search
  :events:
    - heading
    - body
    - author_name
    - author_email
    - metadata
  :pending_induction_submissions:
    - trn
    - date_of_birth
    - trs_first_name
    - trs_last_name
    - trs_email_address
    - error_messages
  :pending_induction_submission_batches:
    - data
    - file_name
  :declarations:
    - voided_by_user_id
  :schools:
    - induction_tutor_name
    - induction_tutor_email
  :mentor_at_school_periods:
    - email
  :ect_at_school_periods:
    - email
  :gias_schools:
    - primary_contact_email
    - secondary_contact_email
