---
:shared:
  :dfe_sign_in_organisations:
    - id
    - name
    - uuid
    - urn
    - address
    - company_registration_number
    - category
    - organisation_type
    - status
    - first_authenticated_at
    - last_authenticated_at
    - created_at
    - updated_at
  :national_bodies:
    - id
    - name
    - dfe_sign_in_organisation_id
    - created_at
    - updated_at
  :teaching_school_hubs:
    - id
    - name
    - dfe_sign_in_organisation_id
    - lead_school_id
    - created_at
    - updated_at
  :legacy_appropriate_bodies:
    - id
    - dqt_id
    - name
    - body_type
    - appropriate_body_period_id
    - created_at
    - updated_at
  :appropriate_bodies:
    - body_type
    - teaching_school_hub_id
    - lead_school_id
    - national_body_id
  :blazer_queries:
    - id
    - creator_id
    - name
    - description
    - statement
    - data_source
    - status
    - created_at
    - updated_at
  :blazer_dashboard_queries:
  - id
  - dashboard_id
  - query_id
  - position
  - created_at
  - updated_at
  :blazer_dashboards:
  - id
  - creator_id
  - name
  - created_at
  - updated_at
  :blazer_checks:
  - id
  - creator_id
  - query_id
  - state
  - schedule
  - emails
  - slack_channels
  - check_type
  - message
  - last_run_at
  - created_at
  - updated_at
  :blazer_audits:
  - id
  - user_id
  - query_id
  - statement
  - data_source
  - created_at
  :solid_queue_semaphores:
  - id
  - key
  - value
  - expires_at
  - created_at
  - updated_at
  :cohorts_lead_providers:
  - id
  - lead_provider_id
  - cohort_id
  - created_at
  - updated_at
  :solid_queue_recurring_tasks:
  - id
  - key
  - schedule
  - command
  - class_name
  - arguments
  - queue_name
  - priority
  - static
  - description
  - created_at
  - updated_at
  :solid_queue_processes:
  - id
  - kind
  - last_heartbeat_at
  - supervisor_id
  - pid
  - hostname
  - metadata
  - created_at
  - name
  :solid_queue_pauses:
  - id
  - queue_name
  - created_at
  :solid_queue_jobs:
  - id
  - queue_name
  - class_name
  - arguments
  - priority
  - active_job_id
  - scheduled_at
  - finished_at
  - concurrency_key
  - created_at
  - updated_at
  :solid_queue_scheduled_executions:
  - id
  - job_id
  - queue_name
  - priority
  - scheduled_at
  - created_at
  :solid_queue_recurring_executions:
  - id
  - job_id
  - task_key
  - run_at
  - created_at
  :solid_queue_ready_executions:
  - id
  - job_id
  - queue_name
  - priority
  - created_at
  :solid_queue_failed_executions:
  - id
  - job_id
  - error
  - created_at
  :solid_queue_claimed_executions:
  - id
  - job_id
  - process_id
  - created_at
  :solid_queue_blocked_executions:
  - id
  - job_id
  - queue_name
  - priority
  - concurrency_key
  - expires_at
  - created_at
  :gias_school_links:
  - id
  - urn
  - link_urn
  - link_type
  - link_date
  - created_at
  - updated_at
  :users:
  - id
  - name
  - email
  - otp_secret
  - otp_verified_at
  - created_at
  - updated_at
  - role
  :teacher_migration_failures:
  - id
  - teacher_id
  - model
  - message
  - migration_item_id
  - migration_item_type
  - created_at
  - updated_at
  :teachers:
  - api_id
  - api_ect_training_record_id
  - api_mentor_training_record_id
  - corrected_name
  - trs_first_name
  - trs_last_name
  - mentor_became_ineligible_for_funding_on
  - mentor_became_ineligible_for_funding_reason
  - ect_payments_frozen_year
  - mentor_payments_frozen_year
  - migration_mode
  - ect_pupil_premium_uplift
  - ect_sparsity_uplift
  - ect_first_became_eligible_for_training_at
  - mentor_first_became_eligible_for_training_at
  - api_updated_at
  - api_unfunded_mentor_updated_at
  :metadata_teachers_lead_providers:
  - id
  - teacher_id
  - lead_provider_id
  - latest_ect_training_period_id
  - latest_mentor_training_period_id
  - latest_ect_contract_period_year
  - latest_mentor_contract_period_year
  - involved_in_school_transfer
  - api_mentor_id
  - created_at
  - updated_at
  :pending_induction_submissions:
  - id
  - appropriate_body_id
  - establishment_id
  - trn
  - date_of_birth
  - induction_programme
  - training_programme
  - started_on
  - finished_on
  - number_of_terms
  - created_at
  - updated_at
  - confirmed_at
  - trs_first_name
  - trs_last_name
  - trs_date_of_birth
  - trs_alerts
  - trs_email_address
  - trs_prohibited_from_teaching
  - trs_induction_start_date
  - trs_induction_completed_date
  - trs_induction_status
  - trs_qts_awarded_on
  - trs_qts_status_description
  - trs_initial_teacher_training_end_date
  - trs_initial_teacher_training_provider_name
  - outcome
  - delete_at
  - confirmed
  - pending_induction_submission_batch_id
  - error_messages
  - fail_confirmation_sent_on
  :pending_induction_submission_batches:
  - data
  - error_message
  - file_name
  :migration_failures:
  - id
  - data_migration_id
  - item
  - failure_message
  - created_at
  - updated_at
  - parent_id
  - parent_type
  :events:
  - id
  - heading
  - body
  - event_type
  - happened_at
  - teacher_id
  - appropriate_body_id
  - induction_period_id
  - induction_extension_id
  - school_id
  - ect_at_school_period_id
  - mentor_at_school_period_id
  - training_period_id
  - mentorship_period_id
  - school_partnership_id
  - lead_provider_id
  - delivery_partner_id
  - active_lead_provider_id
  - lead_provider_delivery_partnership_id
  - pending_induction_submission_batch_id
  - schedule_id
  - statement_id
  - statement_adjustment_id
  - user_id
  - author_type
  - author_id
  - author_name
  - author_email
  - created_at
  - updated_at
  - metadata
  - modifications
  - zendesk_ticket_id
  - declaration_id
  :data_migrations:
  - id
  - model
  - processed_count
  - failure_count
  - started_at
  - completed_at
  - total_count
  - queued_at
  - worker
  - created_at
  - updated_at
  - cache_stats
  :api_tokens:
  - id
  - lead_provider_id
  - token
  - description
  - last_used_at
  - created_at
  - updated_at
  :parity_check_runs:
  - id
  - state
  - mode
  - started_at
  - completed_at
  - created_at
  - updated_at
  :parity_check_requests:
  - id
  - run_id
  - lead_provider_id
  - endpoint_id
  - state
  - started_at
  - completed_at
  - created_at
  - updated_at
  :parity_check_responses:
  - id
  - request_id
  - ecf_status_code
  - rect_status_code
  - ecf_body
  - rect_body
  - ecf_time_ms
  - rect_time_ms
  - ecf_request_uri
  - rect_request_uri
  - request_body
  - match_rate
  - page
  - created_at
  - updated_at
  :parity_check_endpoints:
  - id
  - path
  - method
  - options
  - created_at
  - updated_at
  :metadata_schools_lead_providers_contract_periods:
  - id
  - school_id
  - lead_provider_id
  - contract_period_year
  - expression_of_interest_or_school_partnership
  - created_at
  - updated_at
  :metadata_schools_contract_periods:
  - id
  - school_id
  - contract_period_year
  - in_partnership
  - induction_programme_choice
  - created_at
  - updated_at
  :metadata_delivery_partners_lead_providers:
  - id
  - delivery_partner_id
  - lead_provider_id
  - contract_period_years
  - created_at
  - updated_at
  :teacher_id_changes:
  - id
  - teacher_id
  - api_from_teacher_id
  - api_to_teacher_id
  - ecf_id
  - created_at
  - updated_at
  :support_queries:
  - id
  - state
  - zendesk_id
  - name
  - email
  - school_name
  - school_urn
  - message
  - created_at
  - updated_at
  :data_migration_teacher_combinations:
  - id
  - api_id
  - ecf1_ect_profile_id
  - ecf1_mentor_profile_id
  - ecf1_ect_combinations
  - ecf1_mentor_combinations
  - ecf2_ect_combinations
  - ecf2_mentor_combinations
  - created_at
  - updated_at
  - ecf1_ect_combinations_count
  - ecf1_mentor_combinations_count
  - ecf2_ect_combinations_count
  - ecf2_mentor_combinations_count
  - ecf1_mentorships
  - ecf2_mentorships
  - ecf1_mentorships_count
  - ecf2_mentorships_count
  :data_migration_failed_combinations:
  - id
  - trn
  - profile_id
  - profile_type
  - induction_record_id
  - training_programme
  - school_urn
  - cohort_year
  - lead_provider_name
  - delivery_partner_name
  - start_date
  - end_date
  - induction_status
  - training_status
  - mentor_profile_id
  - schedule_id
  - schedule_identifier
  - schedule_name
  - schedule_cohort_year
  - preferred_identity_email
  - failure_message
  - created_at
  - updated_at
  :data_migration_failed_mentorships:
  - id
  - ect_participant_profile_id
  - mentor_participant_profile_id
  - started_on
  - finished_on
  - ecf_start_induction_record_id
  - ecf_end_induction_record_id
  - failure_message
  - created_at
  - updated_at
  :contract_flat_rate_fee_structures:
  - id
  - recruitment_target
  - fee_per_declaration
  - created_at
  - updated_at
  :contract_banded_fee_structures:
  - id
  - recruitment_target
  - uplift_fee_per_declaration
  - monthly_service_fee
  - setup_fee
  - created_at
  - updated_at
  :contract_banded_fee_structure_bands:
  - id
  - banded_fee_structure_id
  - min_declarations
  - max_declarations
  - fee_per_declaration
  - output_fee_ratio
  - service_fee_ratio
  - created_at
  - updated_at
  :contracts:
  - id
  - contract_type
  - vat_rate
  - flat_rate_fee_structure_id
  - banded_fee_structure_id
  - created_at
  - updated_at
