---
ENVIRONMENT_COLOUR: orange
ENVIRONMENT_PHASE_BANNER_TAG: Migration ðŸ¦”
ENVIRONMENT_PHASE_BANNER_CONTENT: This is the migration environment.
ENABLE_MIGRATION_TESTING: true
ENABLE_SCHOOLS_INTERFACE: true
ENABLE_SENTRY: true
ENABLE_BLAZER: true
ENABLE_FAKE_TRS_API: false
SENTRY_ENVIRONMENT: migration
ENABLE_PERSONAS: false
ENABLE_BULK_UPLOAD: false
ENABLE_BULK_CLAIM: false
ENABLE_PARITY_CHECK: true
SERVICE_URL: "https://cpd-ec2-migration-web.teacherservices.cloud"
DFE_ANALYTICS_ENABLED: false
TRS_API_BASE_URL: "https://preprod.teacher-qualifications-api.education.gov.uk"
TRS_API_VERSION: "20250203"
ENCRYPTION_PRIMARY_KEY: migration_primary_key
ENCRYPTION_DETERMINISTIC_KEY: migration_deterministic_key
ENCRYPTION_DERIVATION_SALT: migration_derivation_salt
RAILS_ENV: migration
PARITY_CHECK_ECF_URL: https://cpd-ecf-migration-web.teacherservices.cloud
PARITY_CHECK_RECT_URL: https://cpd-ec2-migration-web.teacherservices.cloud
