---
ALLOW_INDEXING: false
ENVIRONMENT_COLOUR: pink
ENVIRONMENT_PHASE_BANNER_TAG: Review üîç
ENVIRONMENT_PHASE_BANNER_CONTENT: This is a review application, not a real service
ENABLE_FAKE_TRS_API: false
ENABLE_PERSONAS: true
ENABLE_SCHOOLS_INTERFACE: true
ENABLE_INCIDENT_BANNER: false
ENABLE_API: true
ENABLE_MIGRATION_TESTING: false
TEST_GUIDANCE: true
ENABLE_SENTRY: false
SENTRY_ENVIRONMENT: review
ENABLE_BLAZER: true
DFE_ANALYTICS_ENABLED: false
TRS_API_BASE_URL: 'https://preprod.teacher-qualifications-api.education.gov.uk'
TRS_API_VERSION: '20250203'
ENCRYPTION_PRIMARY_KEY: review_primary_key
ENCRYPTION_DETERMINISTIC_KEY: review_deterministic_key
ENCRYPTION_DERIVATION_SALT: review_derivation_salt
RAILS_ENV: review
ENABLE_TIME_TRAVEL: true
MAX_SESSION_IDLE_TIME: 7200
ENABLE_INDUCTION_TUTOR_PROMPT: true
