---
ALLOW_INDEXING: false
ENVIRONMENT_COLOUR: purple
ENVIRONMENT_PHASE_BANNER_TAG: Staging ðŸŽ¬
ENVIRONMENT_PHASE_BANNER_CONTENT: This is the staging environment.
ENABLE_PERSONAS: true
ENABLE_FAKE_TRS_API: false
ENABLE_PERSONA_AVATARS: false
ENABLE_SCHOOLS_INTERFACE: true
ENABLE_INCIDENT_BANNER: false
ENABLE_APPROPRIATE_BODY_RECORDS_TO_REVIEW: true
TEST_GUIDANCE: true
ENABLE_SENTRY: true
SENTRY_ENVIRONMENT: staging
ENABLE_BLAZER: true
ENABLE_API: true
ENABLE_MIGRATION_TESTING: false
DFE_SIGN_IN_API_AUDIENCE: signin.education.gov.uk
DFE_SIGN_IN_PROFILE: "https://pp-profile.signin.education.gov.uk"
DFE_SIGN_IN_API_BASE_URL: "https://pp-api.signin.education.gov.uk"
DFE_SIGN_IN_CLIENT_ID: RegisterECTs
DFE_SIGN_IN_ISSUER: "https://pp-oidc.signin.education.gov.uk"
DFE_SIGN_IN_REDIRECT_URI: "https://staging.register-early-career-teachers.education.gov.uk/auth/dfe/callback"
DFE_SIGN_IN_SIGN_OUT_REDIRECT_URI: "https://staging.register-early-career-teachers.education.gov.uk/sign-out"
SERVICE_URL: "https://staging.register-early-career-teachers.education.gov.uk"
DFE_ANALYTICS_ENABLED: true
TRS_API_BASE_URL: "https://preprod.teacher-qualifications-api.education.gov.uk"
TRS_API_VERSION: "20260120"
RAILS_ENV: staging
ENABLE_TIME_TRAVEL: true
MAX_SESSION_IDLE_TIME: 7200
